import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { formatDuration, dateLabel } from '../lib/format';
import type { Achievement, Duel, Group, LeaderboardEntry, Session, Stats, UnlockedAchievement, User } from '../types';
import { StatCard } from '../components/StatCard';
import { Loading } from '../components/Loading';
import { LevelProgress } from '../components/LevelProgress';
import { AchievementRack } from '../components/AchievementRack';

interface GroupPulse { group: Group; rank: number; total: number; leader: LeaderboardEntry | null; self: LeaderboardEntry | null }
export function DashboardPage({ user, onStart, onUserUpdate }: { user: User; onStart: () => void; onUserUpdate: (user: User) => void }): JSX.Element {
  const [stats, setStats] = useState<Stats | null>(null); const [sessions, setSessions] = useState<Session[]>([]); const [groups, setGroups] = useState<GroupPulse[]>([]);
  const [achievements, setAchievements] = useState<Achievement[]>([]); const [unlocked, setUnlocked] = useState<UnlockedAchievement[]>([]); const [duels, setDuels] = useState<Duel[]>([]); const [error, setError] = useState(''); const [goal, setGoal] = useState(String(user.dailyGoalMinutes ?? 60)); const [savingGoal, setSavingGoal] = useState(false);
  useEffect(() => { void (async () => { try {
    const [statsResult, sessionResult, groupResult, allAchievements, userAchievements, duelResult] = await Promise.all([api<Stats>('/stats'), api<{ sessions: Session[] }>('/sessions?range=today'), api<{ groups: Group[] }>('/groups'), api<{ achievements: Achievement[] }>('/achievements'), api<{ unlocked: UnlockedAchievement[] }>('/users/me/achievements'), api<{ duels: Duel[] }>('/duels?status=active')]);
    setStats(statsResult); setSessions(sessionResult.sessions); setAchievements(allAchievements.achievements); setUnlocked(userAchievements.unlocked); setDuels(duelResult.duels);
    const pulses = await Promise.all(groupResult.groups.map(async (group) => { const board = await api<{ entries: LeaderboardEntry[] }>(`/groups/${group.id}/leaderboard?range=week`); const self = board.entries.find((item) => item.userId === user.id) ?? null; return { group, rank: self?.rank ?? 0, total: board.entries.reduce((sum, item) => sum + item.totalSeconds, 0), leader: board.entries[0] ?? null, self }; })); setGroups(pulses);
  } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load dashboard.'); } })(); }, [user.id]);
  async function saveGoal(): Promise<void> { setSavingGoal(true); try { const result = await api<{ user: User }>('/users/me/daily-goal', { method: 'PATCH', body: JSON.stringify({ minutes: Number(goal) }) }); onUserUpdate(result.user); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save goal.'); } finally { setSavingGoal(false); } }
  if (!stats) return <Loading />;
  const goalMinutes = user.dailyGoalMinutes ?? 0; const todayMinutes = Math.floor(stats.todaySeconds / 60); const goalPercent = goalMinutes ? Math.min(100, Math.round((todayMinutes / goalMinutes) * 100)) : 0;
  const primaryPulse = groups[0]; const activeDuel = duels[0];
  return <div className="page dashboard"><section className="page-heading"><div><p className="eyebrow">TODAY’S RUN</p><h1>Hey, {user.username}.</h1><p className="streak-line">🔥 {user.currentStreak}-day Streak · Keep the signal alive.</p></div><div className="dashboard-xp"><LevelProgress user={user} compact /></div></section>{error && <p className="form-error">{error}</p>}
    <section className="goal-cta"><article><div><p className="eyebrow">DAILY FOCUS GOAL</p><h2>{goalMinutes ? `${todayMinutes} / ${goalMinutes} min` : 'Set a daily goal'}</h2></div><span>{goalMinutes ? `${goalPercent}%` : 'Ready'}</span><div className="goal-track"><i style={{ width: `${goalPercent}%` }} /></div><div className="goal-controls"><select value={goal} onChange={(event) => setGoal(event.target.value)} aria-label="Daily goal minutes"><option value="60">60 min</option><option value="120">120 min</option><option value="180">180 min</option><option value="240">240 min</option><option value="30">Custom 30 min</option><option value="90">Custom 90 min</option></select><button className="button button-quiet button-small" onClick={() => void saveGoal()} disabled={savingGoal}>Save goal</button></div></article><button className="button button-primary start-button" onClick={onStart}>Start Mission <span>→</span></button></section>
    <section className="stats-grid"><StatCard label="This week" value={formatDuration(stats.weekSeconds)} tone="accent" /><StatCard label="Total XP" value={`${user.xp} XP`} /><StatCard label="Missions today" value={String(sessions.length)} tone="success" /></section>
    <section className="dashboard-columns game-columns"><article className="surface-panel crew-rank"><div className="panel-heading"><div><p className="eyebrow">CREW RANK</p><h2>{primaryPulse?.group.name ?? 'Find your crew'}</h2></div>{primaryPulse && <strong>#{primaryPulse.rank}</strong>}</div>{primaryPulse ? <><p>{primaryPulse.leader?.userId === user.id ? 'You are leading this week.' : `${formatDuration(Math.max(0, (primaryPulse.leader?.totalSeconds ?? 0) - (primaryPulse.self?.totalSeconds ?? 0)))} to catch ${primaryPulse.leader?.username}.`}</p><div className="rank-mini"><span>Group focus</span><b>{formatDuration(primaryPulse.total)}</b></div></> : <p className="empty-copy">Create a private crew to see your rank.</p>}</article><article className="surface-panel duel-summary"><div className="panel-heading"><div><p className="eyebrow">ACTIVE DUEL</p><h2>{activeDuel ? `${activeDuel.type} focus duel` : 'No duel in play'}</h2></div><span>{activeDuel ? '⚔️' : '—'}</span></div><p>{activeDuel ? 'Keep completing missions—the winner is calculated from verified focus time.' : 'Challenge a crew member from the Groups page.'}</p></article></section>
    <section className="dashboard-columns"><article className="surface-panel achievement-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT ACHIEVEMENTS</p><h2>{unlocked.length} / {achievements.length} unlocked</h2></div></div><AchievementRack all={achievements} unlocked={unlocked} limit={6} /></article><article className="surface-panel recent-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT MISSIONS</p><h2>Today</h2></div><span>{formatDuration(stats.todaySeconds)}</span></div>{sessions.length ? <ul className="session-list">{sessions.slice(0, 4).map((session) => <li key={session.id}><div><strong>{session.subject ?? 'Focus mission'}</strong><span>{session.completedAt ? dateLabel(session.completedAt) : ''}</span></div><b>{formatDuration(session.durationSeconds)}</b></li>)}</ul> : <p className="empty-copy">Your completed missions will show up here.</p>}</article></section></div>;
}
