import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../lib/api';
import type { ActivityEvent, Challenge, Duel, Group, LeaderboardEntry, User } from '../types';
import { LeaderboardList } from '../components/LeaderboardList';
import { formatDuration, formatTimeLeft } from '../lib/format';
import { Loading } from '../components/Loading';

type GroupDetail = { group: Group; members: User[] };
type ChallengeData = { challenge: Challenge | null; standings: Omit<LeaderboardEntry, 'rank'>[]; endsInSeconds: number; winnerId?: string; winnerUsername?: string | null; bonusAwarded?: boolean };
function today(): string { return new Date().toISOString().slice(0, 10); }
function weekEnd(): string { const date = new Date(); date.setDate(date.getDate() + 6); return date.toISOString().slice(0, 10); }
function memberName(members: User[], id: string): string { return members.find((member) => member.id === id)?.username ?? id; }
function duelHeadline(duel: Duel, members: User[]): string { return `${duel.challengerUsername ?? memberName(members, duel.challengerId)} vs ${duel.opponentUsername ?? memberName(members, duel.opponentId)}`; }
function duelScore(duel: Duel): string { return `${formatDuration(duel.challengerSeconds ?? 0)} – ${formatDuration(duel.opponentSeconds ?? 0)}`; }
function duelMeta(duel: Duel): string {
  if (duel.status === 'pending') return 'Waiting to accept';
  if (duel.status === 'active') return formatTimeLeft(duel.endsInSeconds ?? 0);
  if (duel.winnerUsername) return `Winner: ${duel.winnerUsername}`;
  if (duel.status === 'completed') return 'Tie';
  return duel.status;
}

export function GroupsPage({ user }: { user: User }): JSX.Element {
  const [groups, setGroups] = useState<Group[] | null>(null); const [selectedId, setSelectedId] = useState(''); const [detail, setDetail] = useState<GroupDetail | null>(null); const [entries, setEntries] = useState<LeaderboardEntry[]>([]); const [range, setRange] = useState<'today' | 'week' | 'month' | 'all_time'>('week'); const [challenge, setChallenge] = useState<ChallengeData | null>(null); const [activity, setActivity] = useState<ActivityEvent[]>([]); const [duels, setDuels] = useState<Duel[]>([]);
  const [newGroup, setNewGroup] = useState(''); const [inviteCode, setInviteCode] = useState(''); const [challengeTitle, setChallengeTitle] = useState('Who can study the most this week?'); const [challengeDescription, setChallengeDescription] = useState(''); const [opponentId, setOpponentId] = useState(''); const [duelType, setDuelType] = useState<'24h' | 'week'>('24h'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  function loadGroups(): void { void api<{ groups: Group[] }>('/groups').then((result) => { setGroups(result.groups); if (result.groups[0]) setSelectedId((current) => current || result.groups[0].id); }).catch((caught: Error) => { setError(caught.message); setGroups([]); }); }
  useEffect(loadGroups, []);
  useEffect(() => { if (!selectedId) { setDetail(null); return; } void (async () => { try { const [groupData, board, currentChallenge, events, userDuels] = await Promise.all([api<GroupDetail>(`/groups/${selectedId}`), api<{ entries: LeaderboardEntry[] }>(`/groups/${selectedId}/leaderboard?range=${range}`), api<ChallengeData>(`/groups/${selectedId}/challenge`), api<{ events: ActivityEvent[] }>(`/groups/${selectedId}/activity`), api<{ duels: Duel[] }>('/duels?status=active')]); setDetail(groupData); setEntries(board.entries); setChallenge(currentChallenge); setActivity(events.events); setDuels(userDuels.duels.filter((duel) => duel.groupId === selectedId)); setOpponentId((current) => current || groupData.members.find((member) => member.id !== user.id)?.id || ''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load group.'); } })(); }, [selectedId, range, user.id]);
  async function createGroup(event: FormEvent): Promise<void> { event.preventDefault(); setBusy(true); setError(''); try { const result = await api<{ group: Group }>('/groups', { method: 'POST', body: JSON.stringify({ name: newGroup }) }); setNewGroup(''); setSelectedId(result.group.id); loadGroups(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not create group.'); } finally { setBusy(false); } }
  async function joinGroup(event: FormEvent): Promise<void> { event.preventDefault(); setBusy(true); setError(''); try { const result = await api<{ group: Group }>('/groups/join', { method: 'POST', body: JSON.stringify({ inviteCode }) }); setInviteCode(''); setSelectedId(result.group.id); loadGroups(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not join group.'); } finally { setBusy(false); } }
  async function createChallenge(event: FormEvent): Promise<void> { event.preventDefault(); if (!selectedId) return; setBusy(true); try { await api('/challenges', { method: 'POST', body: JSON.stringify({ groupId: selectedId, title: challengeTitle, description: challengeDescription || undefined, startDate: today(), endDate: weekEnd() }) }); const result = await api<ChallengeData>(`/groups/${selectedId}/challenge`); setChallenge(result); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not create battle.'); } finally { setBusy(false); } }
  async function createDuel(event: FormEvent): Promise<void> { event.preventDefault(); if (!selectedId || !opponentId) return; setBusy(true); try { const result = await api<{ duel: Duel }>('/duels', { method: 'POST', body: JSON.stringify({ groupId: selectedId, opponentId, type: duelType }) }); setDuels((current) => [result.duel, ...current]); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not create duel.'); } finally { setBusy(false); } }
  async function answerDuel(duel: Duel, action: 'accept' | 'decline'): Promise<void> { try { const result = await api<{ duel: Duel }>(`/duels/${duel.id}/${action}`, { method: 'POST', body: '{}' }); setDuels((current) => current.map((item) => item.id === duel.id ? result.duel : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not update duel.'); } }
  if (!groups) return <Loading />;
  return <div className="page"><section className="page-heading compact"><div><p className="eyebrow">PRIVATE CREWS</p><h1>Groups</h1><p>Shared focus, friendly competition, no noise.</p></div></section>{error && <p className="form-error">{error}</p>}<section className="groups-layout"><aside className="surface-panel group-sidebar"><h2>Your groups</h2><div className="group-nav">{groups.map((group) => <button key={group.id} onClick={() => setSelectedId(group.id)} className={selectedId === group.id ? 'selected' : ''}><strong>{group.name}</strong><span>{group.inviteCode}</span></button>)}</div><form onSubmit={createGroup} className="inline-form"><input value={newGroup} onChange={(event) => setNewGroup(event.target.value)} placeholder="New group name" minLength={2} required /><button className="button button-small" disabled={busy}>Create</button></form><form onSubmit={joinGroup} className="inline-form"><input value={inviteCode} onChange={(event) => setInviteCode(event.target.value.toUpperCase())} placeholder="Invite code" maxLength={6} required /><button className="button button-small button-quiet" disabled={busy}>Join</button></form></aside>
      {detail ? <section className="group-detail"><div className="group-title"><div><p className="eyebrow">GROUP / {detail.group.inviteCode}</p><h2>{detail.group.name}</h2></div><span className="invite-display">Invite <b>{detail.group.inviteCode}</b></span></div><div className="group-detail-grid"><article className="surface-panel"><div className="panel-heading"><h2>Leaderboard</h2><div className="segmented range-control">{(['today', 'week', 'month', 'all_time'] as const).map((item) => <button onClick={() => setRange(item)} className={range === item ? 'active' : ''} key={item}>{item === 'all_time' ? 'All time' : item === 'month' ? 'Month' : item === 'week' ? 'Week' : 'Today'}</button>)}</div></div><LeaderboardList entries={entries} currentUserId={user.id} /></article><article className="surface-panel members-panel"><h2>Members</h2><ul>{detail.members.map((member) => <li key={member.id}><span className="avatar-dot">{member.username.slice(0, 1).toUpperCase()}</span><div><strong>{member.username}</strong><small>{member.id === user.id ? `You · ${member.xp} XP` : `${member.xp} XP`}</small></div></li>)}</ul></article></div>
      <article className="surface-panel battle-panel"><div className="panel-heading"><div><p className="eyebrow">WEEKLY BATTLE</p><h2>{challenge?.challenge?.title ?? 'Set a group target'}</h2></div>{challenge?.challenge && <strong>{challenge.winnerId ? 'Battle complete' : formatTimeLeft(challenge.endsInSeconds)}</strong>}</div>{challenge?.challenge ? <><p>{challenge.winnerUsername ? `Winner: ${challenge.winnerUsername}` : challenge.winnerId ? 'Winner decided from verified mission time.' : challenge.challenge.description || 'Most completed focus time wins the battle.'}</p><ol className="challenge-standings">{challenge.standings.map((entry, index) => <li key={entry.userId} className={entry.userId === challenge.winnerId ? 'is-winner' : ''}><span>{index + 1}</span><b>{entry.username}</b><em>LV {entry.level} · {entry.xp} XP</em><strong>{formatDuration(entry.totalSeconds)}</strong></li>)}</ol></> : <form onSubmit={createChallenge} className="challenge-form"><input value={challengeTitle} onChange={(event) => setChallengeTitle(event.target.value)} minLength={2} required /><input value={challengeDescription} onChange={(event) => setChallengeDescription(event.target.value)} placeholder="Optional prize or note" /><button className="button button-primary" disabled={busy}>Start this week’s Battle</button></form>}</article>
      <div className="group-detail-grid"><article className="surface-panel duel-panel"><div className="panel-heading"><div><p className="eyebrow">FRIEND DUELS</p><h2>Settle it with focus.</h2></div><span>⚔️</span></div>{duels.length ? <ul className="duel-list">{duels.map((duel) => <li key={duel.id}><div><strong>{duelHeadline(duel, detail.members)}</strong><span>{duel.type} · {duelScore(duel)}</span><span>{duelMeta(duel)}</span></div>{duel.status === 'pending' && duel.opponentId === user.id ? <div><button className="button button-small" onClick={() => void answerDuel(duel, 'accept')}>Accept</button><button className="text-button" onClick={() => void answerDuel(duel, 'decline')}>Decline</button></div> : <b>{duel.status}</b>}</li>)}</ul> : <p className="empty-copy">No open duels yet.</p>}<form className="duel-form" onSubmit={createDuel}><select value={opponentId} onChange={(event) => setOpponentId(event.target.value)}>{detail.members.filter((member) => member.id !== user.id).map((member) => <option key={member.id} value={member.id}>{member.username}</option>)}</select><select value={duelType} onChange={(event) => setDuelType(event.target.value as '24h' | 'week')}><option value="24h">24 hours</option><option value="week">1 week</option></select><button className="button button-small button-primary" disabled={busy || !opponentId}>Challenge</button></form></article><article className="surface-panel activity-panel"><p className="eyebrow">CREW ACTIVITY</p><h2>Recent signals</h2>{activity.length ? <ul>{activity.slice(0, 6).map((event) => <li key={event.id}><span className="activity-dot" /><p><b>{event.username}</b> · {event.message}</p></li>)}</ul> : <p className="empty-copy">Completed longer missions, wins, and milestones show here.</p>}</article></div>
      </section> : <section className="surface-panel empty-state"><h2>Make focus social</h2><p>Create a group or join one with an invite code to get started.</p></section>}</section></div>;
}
