import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { formatDuration } from '../lib/format';
import type { Achievement, Group, LeaderboardEntry, Stats, Theme, UnlockedAchievement, User } from '../types';
import { StatCard } from '../components/StatCard';
import { Loading } from '../components/Loading';
import { LevelProgress } from '../components/LevelProgress';
import { AchievementRack } from '../components/AchievementRack';

const themeLabels: Record<Theme, string> = { 'deep-focus': 'Deep focus', 'arcade-neon': 'Arcade neon', 'zen-light': 'Zen light', 'night-owl': 'Night owl' };
interface SubjectStats { breakdown: Array<{ subject: string; seconds: number }>; mostStudied: string | null; totalSessions: number; avgSessionSeconds: number }
export function ProfilePage({ user, theme, onTheme }: { user: User; theme: Theme; onTheme: (theme: Theme) => void }): JSX.Element {
  const [stats, setStats] = useState<Stats | null>(null); const [all, setAll] = useState<Achievement[]>([]); const [unlocked, setUnlocked] = useState<UnlockedAchievement[]>([]); const [subjectStats, setSubjectStats] = useState<SubjectStats | null>(null); const [rank, setRank] = useState<number | null>(null);
  useEffect(() => { void (async () => { const [statsResult, definitions, userAchievements, subjects, groups] = await Promise.all([api<Stats>('/stats'), api<{ achievements: Achievement[] }>('/achievements'), api<{ unlocked: UnlockedAchievement[] }>('/users/me/achievements'), api<SubjectStats>('/stats/subjects?range=week'), api<{ groups: Group[] }>('/groups')]); setStats(statsResult); setAll(definitions.achievements); setUnlocked(userAchievements.unlocked); setSubjectStats(subjects); if (groups.groups[0]) { const board = await api<{ entries: LeaderboardEntry[] }>(`/groups/${groups.groups[0].id}/leaderboard?range=week`); setRank(board.entries.find((item) => item.userId === user.id)?.rank ?? null); } })().catch(() => setStats({ todaySeconds: 0, weekSeconds: 0, totalSeconds: 0, currentStreakDays: 0 })); }, [user.id]);
  if (!stats) return <Loading />;
  return <div className="page profile-page"><section className="gamer-card"><div className="profile-avatar">{user.username.slice(0, 1).toUpperCase()}</div><div className="gamer-intro"><p className="eyebrow">FOCUS PROFILE</p><h1>{user.username}</h1><p>{user.email}</p></div><LevelProgress user={user} /></section><section className="stats-grid"><StatCard label="Total focus" value={formatDuration(stats.totalSeconds)} /><StatCard label="This week" value={formatDuration(stats.weekSeconds)} tone="accent" /><StatCard label="Best streak" value={`${user.longestStreak} days`} tone="success" /></section><section className="profile-detail-grid"><article className="surface-panel"><p className="eyebrow">ACHIEVEMENT CASE</p><h2>Earned progress</h2><AchievementRack all={all} unlocked={unlocked} /><p className="achievement-note">Achievements unlock automatically from verified focus activity.</p></article><article className="surface-panel profile-signal"><p className="eyebrow">THIS WEEK</p><h2>{subjectStats?.mostStudied ?? 'No subject yet'}</h2><ul><li><span>Most studied</span><b>{subjectStats?.mostStudied ?? '—'}</b></li><li><span>Missions completed</span><b>{subjectStats?.totalSessions ?? 0}</b></li><li><span>Average mission</span><b>{formatDuration(subjectStats?.avgSessionSeconds ?? 0)}</b></li><li><span>Group rank</span><b>{rank ? `#${rank}` : '—'}</b></li></ul></article></section><section className="surface-panel theme-panel"><p className="eyebrow">MOOD LAYER</p><h2>Choose today’s workspace.</h2><p>A visual setting only — your progress stays exactly the same.</p><div className="theme-options">{(Object.keys(themeLabels) as Theme[]).map((item) => <button key={item} onClick={() => onTheme(item)} className={`${item} ${theme === item ? 'selected' : ''}`}><span /><strong>{themeLabels[item]}</strong>{theme === item && <small>Active</small>}</button>)}</div></section></div>;
}
